---

- name: Setup SDRAngel
  block:
    - name: Install SDRAngel flatpak
      community.general.flatpak:
        name:
          - org.sdrangel.SDRangel
        state: present
        method: user

    - include_tasks: desktop.yaml