---

- name: Basic setup
  hosts: all
  roles:
    - general/classroom
    - role: geerlingguy.security
      become: true

- name: Install applications
  hosts: classroom
  become: true
  become_user: '{{ classroom.user.name }}'
  roles:
    - general/flatpak
    - general/wallpaper
    - role: apps/sdrangel
      tags:
        - apps
        - sdrangel
    - role: apps/amsat-dl
      tags:
        - apps
        - amsat-dl
