---

collections:
  - name: community.general
    version: 10.7.0

roles:
  - name: geerlingguy.security
    version: 3.0.0
  - name: geerlingguy.docker
    version: 7.7.0
  - name: geerlingguy.ansible
    version: 2.3.0
